import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatCurrency, formatDate } from './formatters'
import { getCategoryLabel } from '../config/categories'

export function generateInsuranceReport(items, user) {
  const doc = new jsPDF({ orientation: 'landscape' })
  const pageW = doc.internal.pageSize.getWidth()
  const now = new Date()

  // Header
  doc.setFillColor(30, 58, 95)
  doc.rect(0, 0, pageW, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('HomeVault — Insurance Inventory Report', 14, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `Prepared for: ${user?.displayName || user?.email || 'Homeowner'}   |   Date: ${formatDate(now.toISOString())}`,
    14,
    30
  )

  // Summary box
  const totalValue = items.reduce((sum, i) => {
    const val = parseFloat(i.currentValue || i.purchasePrice || 0)
    return sum + val * parseFloat(i.quantity || 1)
  }, 0)
  const totalReplacement = items.reduce((sum, i) => {
    const val = parseFloat(i.replacementValue || i.currentValue || i.purchasePrice || 0)
    return sum + val * parseFloat(i.quantity || 1)
  }, 0)

  doc.setTextColor(30, 58, 95)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Summary', 14, 52)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(`Total Items: ${items.length}`, 14, 60)
  doc.text(`Total Current Value: ${formatCurrency(totalValue)}`, 80, 60)
  doc.text(`Total Replacement Value: ${formatCurrency(totalReplacement)}`, 180, 60)

  // Table
  const head = [
    ['Item Name', 'Brand/Model', 'Category', 'Location', 'Serial #', 'Purchase Date', 'Current Value', 'Replacement Value', 'Warranty'],
  ]
  const body = items.map((i) => [
    i.name || '—',
    [i.brand, i.model].filter(Boolean).join(' / ') || '—',
    getCategoryLabel(i.category),
    i.location || '—',
    i.serialNumber || '—',
    formatDate(i.purchaseDate),
    formatCurrency(parseFloat(i.currentValue || i.purchasePrice || 0)),
    formatCurrency(parseFloat(i.replacementValue || i.currentValue || i.purchasePrice || 0)),
    i.warrantyExpiry ? formatDate(i.warrantyExpiry) : '—',
  ])

  autoTable(doc, {
    startY: 68,
    head,
    body,
    headStyles: {
      fillColor: [13, 148, 136],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [15, 23, 42],
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 38 },
      2: { cellWidth: 30 },
      3: { cellWidth: 28 },
      4: { cellWidth: 30 },
      5: { cellWidth: 25 },
      6: { cellWidth: 28 },
      7: { cellWidth: 30 },
      8: { cellWidth: 25 },
    },
    margin: { left: 14, right: 14 },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139)
    doc.text(
      `Page ${i} of ${pageCount} — Generated by HomeVault on ${now.toLocaleDateString()}`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    )
  }

  doc.save(`HomeVault_Insurance_Report_${now.toISOString().split('T')[0]}.pdf`)
}

export function generateInventoryReport(items, filters = {}) {
  const doc = new jsPDF()
  const pageW = doc.internal.pageSize.getWidth()
  const now = new Date()

  // Header
  doc.setFillColor(30, 58, 95)
  doc.rect(0, 0, pageW, 35, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('HomeVault — Inventory Report', 14, 16)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated: ${formatDate(now.toISOString())}  |  Items: ${items.length}`, 14, 26)

  // Filter info
  if (filters.category || filters.location || filters.search) {
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(9)
    const filterParts = []
    if (filters.category) filterParts.push(`Category: ${getCategoryLabel(filters.category)}`)
    if (filters.location) filterParts.push(`Location: ${filters.location}`)
    if (filters.search) filterParts.push(`Search: "${filters.search}"`)
    doc.text(`Filters: ${filterParts.join(' | ')}`, 14, 44)
  }

  const startY = filters.category || filters.location || filters.search ? 50 : 44

  const head = [['Name', 'Category', 'Location', 'Qty', 'Condition', 'Purchase Date', 'Value']]
  const body = items.map((i) => [
    i.name || '—',
    getCategoryLabel(i.category),
    i.location || '—',
    `${i.quantity || 1} ${i.unit || ''}`.trim(),
    i.condition || '—',
    formatDate(i.purchaseDate),
    formatCurrency(parseFloat(i.currentValue || i.purchasePrice || 0)),
  ])

  autoTable(doc, {
    startY,
    head,
    body,
    headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    margin: { left: 14, right: 14 },
  })

  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    )
  }

  doc.save(`HomeVault_Inventory_${now.toISOString().split('T')[0]}.pdf`)
}
